services:

  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    container_name: iceduck_trino
    env_file: "./etc/iceduck.env"
    ports:
      - ${TRINO_UI_PORT}:8080
    volumes:
      - ./files/data/trino/etc:/etc/trino
      - ./files/data/trino/data:/data
    networks:
      iceberg_net:
        aliases:
          - trino


  polaris:
    image: apache/polaris:latest
    container_name: iceduck_polaris
    ports:
      # API port
      - ${POLARIS_API_PORT}:8181
      # Management port (metrics and health checks)
      - ${POLARIS_MGMT_PORT}:8182
      - 8040:8080
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_started
    env_file: "./etc/iceduck.env"
    environment:
      - polaris.realm-context.realms=${POLARIS_REALM}
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${POLARIS_MGMT_PORT}/q/health"]
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      iceberg_net:
        aliases:
          - rest

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: iceduck_minio
    env_file: "./etc/iceduck.env"
    volumes:
        - ./files/data/minio:/data
    ports:
      - ${MINIO_UI_PORT}:9001
      - ${MINIO_API_PORT}:9000
    command: ["server", "/data", "--console-address", ":${MINIO_UI_PORT}"]
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1:${MINIO_API_PORT}/minio/health/live"]
      interval: 1s
      timeout: 10s
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio

  postgres:
    build:
      context: .
      dockerfile: ./files/docker/postgres/Dockerfile
    container_name: iceduck_db
    ports: 
      - ${POSTGRES_PORT}:5432
    env_file: "./etc/iceduck.env"
    volumes:
      - ./files/data/postgres/data:/var/lib/postgresql/data
      - ./files/docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      iceberg_net:
        aliases:
          - database

  curlshell:
    build:
      context: .
      dockerfile: ./files/docker/curlshell/Dockerfile

  spark:
    build: ./files/docker/spark
    container_name: iceduck_spark
    depends_on:
      - polaris
      - minio
    volumes:
      - ./files/data/spark/config/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./files/data/spark/config/pyiceberg.yaml:/root/.pyiceberg.yaml
      - ./files/data/spark/warehouse:/home/iceberg/warehouse
      - ./files/scripts/jupyter:/home/iceberg/notebooks
    env_file: "./etc/iceduck.env"
    ports:
      - ${SPARK_JUPYTER_PORT}:8888
      - ${SPARK_UI_PORT}:8080
      - 10000:10000
      - 10001:10001
    networks:
      iceberg_net:


networks:
  iceberg_net:

