#!/bin/bash

_prep_folders() {
        mkdir -p ./files/data/mc \
        ./files/data/postgres/data \
        ./files/data/minio \
        ./files/data/trino/data \
        ./files/data/trino/etc/catalog \
        ./files/data/spark/config \
        ./files/data/spark/warehouse \
        ./files/data/spark/notebooks \
        ./files/data/duckdb/workspace/init
}

_abort() {
        ERRORCODE=$1

        echo "Script ended unsuccessfull with $ERRORCODE"
        exit $ERRORCODE
}

START_DIR=$PWD
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

set -a
source ./etc/iceduck.env

case $1 in
    init)   echo "Initializing"

            echo "----- Datenverzeichnisse anlegen"
            _prep_folders 
            [ $? -ne 0 ] && { _abort 10; }

            echo "----- Trino config schreiben"
            ./files/init/prep_trino.sh
            [ $? -ne 0 ] && { _abort 10; }

            echo "----- configure Spark"
            ./files/init/prep_spark.sh
            [ $? -ne 0 ] && { _abort 10; }

            echo "----- configure DuckDB"
            ./files/init/prep_duckdb.sh
            [ $? -ne 0 ] && { _abort 10; }

            echo "----- prepare the Docker network"
            docker network inspect iceduck_net 2>&1 >/dev/null
            [ $? -ne 0 ] && {
                 docker network create -d bridge iceduck_net
                 [ $? -ne 0 ] && { _abort 10; }
	    }

            echo "----- Stack starten"
            docker compose -f files/docker/docker-compose.yaml up -d
            [ $? -ne 0 ] && { _abort 10; }

            echo "----- Bucket im Minio anlegen"
            bin/mc -f ./files/init/prep_minio.sh
            [ $? -ne 0 ] && { _abort 10; }

            echo "----- bootstrap Polaris"
            bin/poladm -c "bootstrap -r \${POLARIS_REALM} -c \${POLARIS_REALM},\${POLARIS_ROOT_CLIENT_ID},\${POLARIS_ROOT_CLIENT_SECRET} --print-credentials"
            [ $? -ne 0 ] && { _abort 10; }

            echo "----- configure Polaris"
            bin/iceshell -f ./files/init/prep_polaris.sh
            [ $? -ne 0 ] && { _abort 10; }

            ;;
    build)  docker compose -f files/docker/docker-compose.yaml build
            [ $? -ne 0 ] && { _abort 10; }
            ;;
    clean)
            docker compose -f files/docker/docker-compose.yaml down
            [ $? -ne 0 ] && { _abort 10; }

            echo "----- prepare the Docker network"
            docker network inspect iceduck_net 2>&1 >/dev/null
            [ $? -eq 0 ] && {
	    	docker network rm iceduck_net
            	[ $? -ne 0 ] && { _abort 10; }
	    }

            sudo rm -rf ./files/data/*
            [ $? -ne 0 ] && { _abort 10; }

            _prep_folders
            [ $? -ne 0 ] && { _abort 10; }

            ;;
    start)  docker compose -f files/docker/docker-compose.yaml up -d  
            [ $? -ne 0 ] && { _abort 10; }
            ;;
    stop)   docker compose -f files/docker/docker-compose.yaml down
            [ $? -ne 0 ] && { _abort 10; }
            ;;
    restart)   docker compose -f files/docker/docker-compose.yaml down && docker compose -f files/docker/docker-compose.yaml up -d 
            [ $? -ne 0 ] && { _abort 10; }
            ;;
    *)      ;;
esac    

cd $START_DIR
exit $ECODE

