#!/bin/bash

set -a
source ./etc/iceduck.env

case $1 in
    init)   echo "Initializing"

            echo "----- Trino config schreiben"
            ./files/init/prep_trino.sh

            echo "----- configure Spark"
            ./files/init/prep_spark.sh

            echo "----- Stack starten"
            docker compose up -d

            echo "----- Bucket im Minio anlegen"
            bin/mc ./files/init/prep_minio.sh

            echo "----- bootstrap Polaris"
            bin/poladm bootstrap -r ${POLARIS_REALM} -c "${POLARIS_REALM},${POLARIS_ROOT_CLIENT_ID},${POLARIS_ROOT_CLIENT_SECRET}" --print-credentials

            echo "----- configure Polaris"
            bin/iceshell ./files/init/prep_polaris.sh

            ;;
    clean)
            docker compose down
            sudo rm -rf ./files/data/*
            mkdir -p ./files/data/mc \
                ./files/data/postgres/data \
                ./files/data/minio \
                ./files/data/trino/data \
                ./files/data/trino/etc/catalog \
                ./files/data/spark/config \
                ./files/data/spark/warehouse \
                ./files/data/spark/notebooks \
            ;;
    start)   docker compose up -d ;;
    stop)   docker compose down ;;
    restart)   docker compose down && docker compose up -d ;;
    *)      ;;
esac    


