#!/bin/bash

#
#  ICEDUCK DATABASE
#
psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL

CREATE USER ${ICEDUCK_DB_USER} WITH PASSWORD '${ICEDUCK_DB_PASSWORD}';
CREATE DATABASE ${ICEDUCK_DB_NAME};
GRANT ALL PRIVILEGES ON DATABASE ${ICEDUCK_DB_NAME} TO ${ICEDUCK_DB_USER};

\c ${ICEDUCK_DB_NAME}

GRANT ALL ON SCHEMA public TO ${ICEDUCK_DB_USER};
CREATE EXTENSION pg_duckdb;

EOSQL