#!/bin/bash

#
#  POLARIS METASTORE
#

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL

CREATE USER ${QUARKUS_DATASOURCE_USERNAME} WITH PASSWORD '${QUARKUS_DATASOURCE_PASSWORD}';
CREATE DATABASE ${QUARKUS_DATASOURCE_NAME};
GRANT ALL PRIVILEGES ON DATABASE ${QUARKUS_DATASOURCE_NAME} TO ${QUARKUS_DATASOURCE_USERNAME};

\c ${QUARKUS_DATASOURCE_NAME}

GRANT ALL ON SCHEMA public TO ${QUARKUS_DATASOURCE_USERNAME};

EOSQL
